### ISSUE TITLE
Home Assistant 0.117.4 not starting

### ISSUE THREAD

**Issue by Hambootje** [tprelog/iocage-homeassistant#29]
Hi,

Today I updated Home Assistant to 0.117.4 but it's not starting properly. 

In the logfile I can see an error related to openSSL:

2020-10-30 18:26:54 ERROR (MainThread) [homeassistant.setup] Setup failed for cloud: unknown error
Traceback (most recent call last):
File "/usr/local/share/homeassistant/lib/python3.8/site-packages/homeassistant/setup.py", line 166, in _async_setup_component
component = integration.get_component()
File "/usr/local/share/homeassistant/lib/python3.8/site-packages/homeassistant/loader.py", line 414, in get_component
cache[self.domain] = importlib.import_module(self.pkg_path)
File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
File "<frozen importlib._bootstrap>", line 991, in _find_and_load
File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 783, in exec_module
File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
File "/usr/local/share/homeassistant/lib/python3.8/site-packages/homeassistant/components/cloud/__init__.py", line 2, in <module>
from hass_nabucasa import Cloud
File "/usr/local/share/homeassistant/lib/python3.8/site-packages/hass_nabucasa/__init__.py", line 14, in <module>
from .auth import CognitoAuth
File "/usr/local/share/homeassistant/lib/python3.8/site-packages/hass_nabucasa/auth.py", line 7, in <module>
import boto3
File "/usr/local/share/homeassistant/lib/python3.8/site-packages/boto3/__init__.py", line 16, in <module>
from boto3.session import Session
File "/usr/local/share/homeassistant/lib/python3.8/site-packages/boto3/session.py", line 17, in <module>
import botocore.session
File "/usr/local/share/homeassistant/lib/python3.8/site-packages/botocore/session.py", line 30, in <module>
import botocore.credentials
File "/usr/local/share/homeassistant/lib/python3.8/site-packages/botocore/credentials.py", line 34, in <module>
from botocore.config import Config
File "/usr/local/share/homeassistant/lib/python3.8/site-packages/botocore/config.py", line 16, in <module>
from botocore.endpoint import DEFAULT_TIMEOUT, MAX_POOL_CONNECTIONS
File "/usr/local/share/homeassistant/lib/python3.8/site-packages/botocore/endpoint.py", line 22, in <module>
from botocore.awsrequest import create_request_object
File "/usr/local/share/homeassistant/lib/python3.8/site-packages/botocore/awsrequest.py", line 25, in <module>
import botocore.utils
File "/usr/local/share/homeassistant/lib/python3.8/site-packages/botocore/utils.py", line 32, in <module>
import botocore.httpsession
File "/usr/local/share/homeassistant/lib/python3.8/site-packages/botocore/httpsession.py", line 17, in <module>
from urllib3.contrib.pyopenssl import orig_util_SSLContext as SSLContext
File "/usr/local/share/homeassistant/lib/python3.8/site-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
import OpenSSL.SSL
File "/usr/local/share/homeassistant/lib/python3.8/site-packages/OpenSSL/__init__.py", line 8, in <module>
from OpenSSL import crypto, SSL
File "/usr/local/share/homeassistant/lib/python3.8/site-packages/OpenSSL/crypto.py", line 15, in <module>
from OpenSSL._util import (
File "/usr/local/share/homeassistant/lib/python3.8/site-packages/OpenSSL/_util.py", line 6, in <module>
from cryptography.hazmat.bindings.openssl.binding import Binding
File "/usr/local/share/homeassistant/lib/python3.8/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 222, in <module>
_verify_openssl_version(Binding.lib)
File "/usr/local/share/homeassistant/lib/python3.8/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 182, in _verify_openssl_version
raise RuntimeError(
RuntimeError: You are linking against OpenSSL 1.0.2, which is no longer supported by the OpenSSL project. To use this version of cryptography you need to upgrade to a newer version of OpenSSL. For this version only you can also set the environment variable CRYPTOGRAPHY_ALLOW_OPENSSL_102 to allow OpenSSL 1.0.2.

Creating a new jail also results in the same error.
Is this related to my setup or is the plugin not working correctly for 0.177.4?

Kind regards,
Berry

**Comment by tprelog** [comment]
The 11.3-RELEASE is past EOL so this plugin has been falling apart for people on FreeNAS - I am unaware of any plans for ix-systems to switch _plugins_ to the next (11.4) release on _FreeNAS_. Unfortunately, it seems continuing to support this plugin on 11.3 is beyond my ability.

If it's possible for you to upgrade (or when you do upgrade) using this plugin on _TrueNAS Core_ is best option - An updated OpenSSL is already included in the FreeBSD base, which requires no workarounds for Home Assistant. Other issue that are appearing, related to the 11.3-RELEASE, simply do not exist.

This leaves two options:
1. Manually creating an 11.4-RELEASE jail on FreeNAS 11.3
2. Switch your FreeNAS to the TrueNAS-12.0-Stable train

I have not found a way to make a _plugin_ on FreeNAS use the 11.4-RELEASE - This can only be done by manually creating jail. If you would like to go this route. I'm not sure if using the 11.4-RELEASE will be enough to resolve the OpenSSL issue you reported here. [You might still need to manually updating OpenSSL](https://github.com/tprelog/iocage-homeassistant/wiki/openssl-and-HomeKit#to-fix-or-update-openssl-using-the-community-plugin)

The link is intended for FreeNAS users only (not TrueNAS Core) - you are still welcome to try the steps listed there and it might enough to solve your current issue. However, I still fear you may encounter other issues related to the 11.3-RELEASE being past EOL.


There are 5 - 6 people who have opted for upgrading to TrueNAS Core. So far, everyone has been able to restore Home Assistant to full functionality after doing so.

**Comment by Hambootje** [comment]
I have updated Freenas 11.3 to TrueNas 12.0. Upgrading the existing HomeAssistant jail did not work.
Creating a new jail with the plugin worked fine! I copied my data to this new jail and things are up and running now.
Thank you so much!
