### ISSUE TITLE
Errors updating to 0.117.1 on FreeNAS

### ISSUE THREAD

**Issue by gajotnt** [tprelog/iocage-homeassistant#30]
Got these errors while updating to lastest version.

![HA](https://user-images.githubusercontent.com/25504364/97788093-1ecddf00-1bae-11eb-9322-f65b779d5ab5.PNG)

**Comment by gajotnt** [comment]
```
2020-10-31 18:18:43 ERROR (MainThread) [homeassistant.setup] Setup failed for cloud: unknown error
Traceback (most recent call last):
File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/setup.py", line 166, in _async_setup_component
component = integration.get_component()
File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/loader.py", line 414, in get_component
cache[self.domain] = importlib.import_module(self.pkg_path)
File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
File "<frozen importlib._bootstrap>", line 983, in _find_and_load
File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 728, in exec_module
File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/cloud/__init__.py", line 2, in <module>
from hass_nabucasa import Cloud
File "/srv/homeassistant/lib/python3.7/site-packages/hass_nabucasa/__init__.py", line 14, in <module>
from .auth import CognitoAuth
File "/srv/homeassistant/lib/python3.7/site-packages/hass_nabucasa/auth.py", line 7, in <module>
import boto3
File "/srv/homeassistant/lib/python3.7/site-packages/boto3/__init__.py", line 16, in <module>
from boto3.session import Session
File "/srv/homeassistant/lib/python3.7/site-packages/boto3/session.py", line 17, in <module>
import botocore.session
File "/srv/homeassistant/lib/python3.7/site-packages/botocore/session.py", line 29, in <module>
import botocore.credentials
File "/srv/homeassistant/lib/python3.7/site-packages/botocore/credentials.py", line 34, in <module>
from botocore.config import Config
File "/srv/homeassistant/lib/python3.7/site-packages/botocore/config.py", line 16, in <module>
from botocore.endpoint import DEFAULT_TIMEOUT, MAX_POOL_CONNECTIONS
File "/srv/homeassistant/lib/python3.7/site-packages/botocore/endpoint.py", line 22, in <module>
from botocore.awsrequest import create_request_object
File "/srv/homeassistant/lib/python3.7/site-packages/botocore/awsrequest.py", line 25, in <module>
import botocore.utils
File "/srv/homeassistant/lib/python3.7/site-packages/botocore/utils.py", line 31, in <module>
import botocore.httpsession
File "/srv/homeassistant/lib/python3.7/site-packages/botocore/httpsession.py", line 17, in <module>
from urllib3.contrib.pyopenssl import orig_util_SSLContext as SSLContext
File "/srv/homeassistant/lib/python3.7/site-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
import OpenSSL.SSL
File "/srv/homeassistant/lib/python3.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
from OpenSSL import crypto, SSL
File "/srv/homeassistant/lib/python3.7/site-packages/OpenSSL/crypto.py", line 15, in <module>
from OpenSSL._util import (
File "/srv/homeassistant/lib/python3.7/site-packages/OpenSSL/_util.py", line 6, in <module>
from cryptography.hazmat.bindings.openssl.binding import Binding
File "/srv/homeassistant/lib/python3.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 222, in <module>
_verify_openssl_version(Binding.lib)
File "/srv/homeassistant/lib/python3.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 183, in _verify_openssl_version
"You are linking against OpenSSL 1.0.2, which is no longer "
RuntimeError: You are linking against OpenSSL 1.0.2, which is no longer supported by the OpenSSL project. To use this version of cryptography you need to upgrade to a newer version of OpenSSL. For this version only you can also set the environment variable CRYPTOGRAPHY_ALLOW_OPENSSL_102 to allow OpenSSL 1.0.2.
2020-10-31 18:18:45 ERROR (MainThread) [homeassistant.components.fan] xiaomi_miio: Error on device update!
Traceback (most recent call last):
File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity_platform.py", line 357, in _async_add_entity
await entity.async_device_update(warning=False)
File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 466, in async_device_update
await task
File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/xiaomi_miio/fan.py", line 777, in async_update
state = await self.hass.async_add_executor_job(self._device.status)
File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
result = self.fn(*self.args, **self.kwargs)
File "/srv/homeassistant/lib/python3.7/site-packages/miio/airpurifier.py", line 412, in status
values = self.get_properties(properties, max_properties=15)
File "/srv/homeassistant/lib/python3.7/site-packages/miio/device.py", line 232, in get_properties
values.extend(self.send(property_getter, _props[:max_properties]))
File "/srv/homeassistant/lib/python3.7/site-packages/miio/device.py", line 147, in send
command, parameters, retry_count, extra_parameters=extra_parameters
File "/srv/homeassistant/lib/python3.7/site-packages/miio/miioprotocol.py", line 173, in send
m = Message.build(msg, token=self.token)
File "/srv/homeassistant/lib/python3.7/site-packages/construct/core.py", line 352, in build
self.build_stream(obj, stream, **contextkw)
File "/srv/homeassistant/lib/python3.7/site-packages/construct/core.py", line 364, in build_stream
self._build(obj, stream, context, "(building)")
File "/srv/homeassistant/lib/python3.7/site-packages/construct/core.py", line 2003, in _build
buildret = sc._build(subobj, stream, context, path)
File "/srv/homeassistant/lib/python3.7/site-packages/construct/core.py", line 2472, in _build
return self.subcon._build(obj, stream, context, path)
File "/srv/homeassistant/lib/python3.7/site-packages/construct/core.py", line 4078, in _build
buildret = self.subcon._build(obj, stream, context, path)
File "/srv/homeassistant/lib/python3.7/site-packages/construct/core.py", line 4365, in _build
buildret = self.subcon._build(value, stream, context, path)
File "/srv/homeassistant/lib/python3.7/site-packages/construct/core.py", line 718, in _build
obj2 = self._encode(obj, context, path)
File "/srv/homeassistant/lib/python3.7/site-packages/miio/protocol.py", line 159, in _encode
json.dumps(obj).encode("utf-8") + b"\x00", context["_"]["token"]
File "/srv/homeassistant/lib/python3.7/site-packages/miio/protocol.py", line 85, in encrypt
cipher = Cipher(algorithms.AES(key), modes.CBC(iv), backend=default_backend())
File "/srv/homeassistant/lib/python3.7/site-packages/cryptography/hazmat/backends/__init__.py", line 15, in default_backend
from cryptography.hazmat.backends.openssl.backend import backend
File "/srv/homeassistant/lib/python3.7/site-packages/cryptography/hazmat/backends/openssl/__init__.py", line 7, in <module>
from cryptography.hazmat.backends.openssl.backend import backend
File "/srv/homeassistant/lib/python3.7/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 117, in <module>
from cryptography.hazmat.bindings.openssl import binding
File "/srv/homeassistant/lib/python3.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 222, in <module>
_verify_openssl_version(Binding.lib)
File "/srv/homeassistant/lib/python3.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 183, in _verify_openssl_version
"You are linking against OpenSSL 1.0.2, which is no longer "
RuntimeError: You are linking against OpenSSL 1.0.2, which is no longer supported by the OpenSSL project. To use this version of cryptography you need to upgrade to a newer version of OpenSSL. For this version only you can also set the environment variable CRYPTOGRAPHY_ALLOW_OPENSSL_102 to allow OpenSSL 1.0.2.
```

**Comment by tprelog** [comment]
Hi @gajotnt - I'm sorry your having trouble.

 You can [try following these steps to update openssl.](https://github.com/tprelog/iocage-homeassistant/wiki/openssl-and-HomeKit#to-fix-or-update-openssl-using-the-community-plugin) However, if you run into additional issues while trying these, I may not be able to help. I am having a hard time continuing to support this plugin using the 11.3-RELEASE.

---

**PLEASE BEWARE** – The 11.3-RELEASE is now past it’s EOL date. This has been causing various issues in this plugins, that seem beyond my control. From the limited number of Google results I could find, the solution is upgrading to a supported RELEASE. Basically as packages in the FreeBSD repos have been updated, some are no longer compatible with the 11.3-RELEASE. At this time, ix-systems has no plans for switching the _**FreeNAS** plugins_ to the 11.4-RELEASE :disappointed:

This leaves two options:

1. Manually creating an 11.4-RELEASE jail on FreeNAS 11.3
2. Switch your FreeNAS to the TrueNAS-12.0-Stable train

I have not found a way to make a plugin on FreeNAS use the 11.4-RELEASE - This can only be done by manually creating jail. If you would like to go this route. I'm not sure if using the 11.4-RELEASE will be enough to resolve the OpenSSL issue you reported here. You might still need to manually update OpenSSL according to the link. _The link is intended for FreeNAS users_ only (not TrueNAS Core)

There are several people who have opted for upgrading to TrueNAS Core. So far, everyone has been able to restore Home Assistant to full functionality after doing so. If your ready to upgrade, I think this is the best option. An updated OpenSSL is already included in the FreeBSD base, which requires no workarounds for Home Assistant. Other issue that are appearing, related to the 11.3-RELEASE, simply do not exist. If you chose this route, I can help you upgrade your existing plugin and get Home Assistant running again. -- This plugin is currently running 12.2-RC3 release when installed on TrueNAS Core

In any case, a few other things --

Home Assistant is installed in a virtualenv, the virtualenv is intended to be disposable and can be recreated at any time without re-installing the entire plugin.

_**Your configuration is stored separately in the HOME folder. Even if it is impossible to recover Home Assistant, as long as you do not destroy the jail, you configuration can still be saved.**_

**Comment by tprelog** [comment]
I've started a wiki page, that might help if you decide to upgrade to TrueNAS Core

[Plugin Upgrade from FreeNAS to TrueNAS Core](https://github.com/tprelog/iocage-homeassistant/wiki/Plugin-Upgrade---From-FreeNAS-to-TrueNAS-Core)

**Comment by gajotnt** [comment]
Thanks, made a backup of the files, and made a new jail with all your new changes.

Sorry for posting here without reading more into the new truenas update.

**Comment by tprelog** [comment]
>Sorry for posting here without reading more into the new truenas update.

No worries, I pinned this because I think everyone using the _FreeNAS version_ of this plugin will have issue with OpensSSL when upgrading to `0.117.1`or later  - Combined with other issues, related to the 11.3-RELEASE being EOL, this OpenSSL update is likely the final blow for the Home Assistant plugin on _FreeNAS_
