### ISSUE TITLE
Upgrade to HA 2021.10 requires libjpeg-turbo

### ISSUE THREAD

**Issue by adorobis** [tprelog/iocage-homeassistant#46]
After upgrading HA to 2021.10 release the following error starts to be logged:
```
2021-10-07 18:22:52 ERROR (MainThread) [homeassistant.components.camera.img_util] Error loading libturbojpeg; Cameras may impact HomeKit performance
Traceback (most recent call last):
  File "/usr/local/share/homeassistant/lib/python3.8/site-packages/homeassistant/components/camera/img_util.py", line 96, in __init__
    TurboJPEGSingleton.__instance = TurboJPEG()
  File "/usr/local/share/homeassistant/lib/python3.8/site-packages/turbojpeg.py", line 287, in __init__
    self.__init_decompress = turbo_jpeg.tjInitDecompress
  File "/usr/local/lib/python3.8/ctypes/__init__.py", line 386, in __getattr__
    func = self.__getitem__(name)
  File "/usr/local/lib/python3.8/ctypes/__init__.py", line 391, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: Undefined symbol "tjInitDecompress"
```
Installing `libjpeg-turbo` satisfices this dependency
`pkg install libjpeg-turbo`
Probably needs to be added to HA plugin dependencies.

**Comment by tprelog** [comment]
This should be resolved for some some time now.
